services:
  - type: worker
    name: zionix-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID_STR
        sync: false
      - key: ADMIN_ID_STR
        sync: false
      - key: YOUR_USERNAME
        sync: false
      - key: UPDATE_CHANNEL
        sync: false
